import type { NextApiRequest, NextApiResponse } from 'next';
import { ResponseLaporanRekapitulasi } from '@/models/MLaporanRekapitulasi';

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseLaporanRekapitulasi>
) {
  if (req.method !== 'GET') {
    return res.status(405).json({
      success: false,
      code: 405,
      message: 'Method not allowed',
      data: {} as any,
      timestamp: Date.now(),
      timezone: {
        timezone_type: 3,
        timezone: 'Asia/Jakarta'
      }
    });
  }

  // Mock data yang sesuai dengan interface MLaporanRekapitulasi
  const mockData: ResponseLaporanRekapitulasi = {
    success: true,
    code: 200,
    message: 'Data laporan rekapitulasi berhasil diambil',
    data: {
      total_seluruh_limbah: 2500.75,
      total_seluruh_limbah_b3: 1200.50,
      total_seluruh_limbah_covid: 800.25,
      total_seluruh_limbah_noncovid: 400.25,
      total_seluruh_limbah_b3_nonmedis: 300.00,
      total_seluruh_limbah_b3_medis: 900.50,
      total_seluruh_limbah_jarum: 150.75,
      total_seluruh_limbah_sludge_ipal: 450.00,
      tahun: '2024',
      users: [
        {
          id_user: 1,
          username: 'puskesmas_001',
          nama_user: 'Puskesmas Pancoran Mas',
          level: 2,
          noreg_tempat: 'PKM001',
          tipe_tempat: 'Puskesmas',
          nama_tempat: 'Puskesmas Pancoran Mas',
          alamat_tempat: 'Jl. Margonda Raya No. 1, Depok',
          id_kelurahan: 1,
          id_kecamatan: 1,
          kelurahan: 'Pancoran Mas',
          kecamatan: 'Pancoran Mas',
          notlp: '021-7720001',
          nohp: '081234567890',
          email: 'puskesmas001@depok.go.id',
          izin_ipal: 'IPAL001',
          izin_tps: 'TPS001',
          status_user: 1,
          statusactive_user: 1,
          user_created: 'admin',
          user_updated: 'admin',
          uid: 'uuid-001',
          created_at: '2024-01-01T00:00:00.000Z',
          updated_at: '2024-01-15T10:30:00.000Z',
          limbah: 450.25,
          limbah_b3: 200.50,
          limbah_noncovid: 150.75,
          limbah_covid: 99.00
        },
        {
          id_user: 2,
          username: 'rs_001',
          nama_user: 'RS Umum Depok',
          level: 3,
          noreg_tempat: 'RS001',
          tipe_tempat: 'Rumah Sakit',
          nama_tempat: 'RS Umum Depok',
          alamat_tempat: 'Jl. Siliwangi No. 50, Depok',
          id_kelurahan: 2,
          id_kecamatan: 2,
          kelurahan: 'Beji',
          kecamatan: 'Beji',
          notlp: '021-7720002',
          nohp: '081234567891',
          email: 'rs001@depok.go.id',
          izin_ipal: 'IPAL002',
          izin_tps: 'TPS002',
          status_user: 1,
          statusactive_user: 1,
          user_created: 'admin',
          user_updated: 'admin',
          uid: 'uuid-002',
          created_at: '2024-01-01T00:00:00.000Z',
          updated_at: '2024-01-15T10:30:00.000Z',
          limbah: 850.50,
          limbah_b3: 500.25,
          limbah_noncovid: 200.25,
          limbah_covid: 150.00
        }
      ],
      laporan: [
        {
          periode: 1,
          periode_nama: 'Januari',
          total_limbah: 1200.50,
          total_limbah_b3: 600.25,
          total_limbah_covid: 400.00,
          total_limbah_noncovid: 200.25,
          total_limbah_b3_nonmedis: 150.00,
          total_limbah_b3_medis: 450.25,
          total_limbah_jarum: 75.50,
          total_limbah_sludge_ipal: 225.00,
          users: [
            {
              id_user: 1,
              username: 'puskesmas_001',
              nama_user: 'Puskesmas Pancoran Mas',
              level: 2,
              noreg_tempat: 'PKM001',
              tipe_tempat: 'Puskesmas',
              nama_tempat: 'Puskesmas Pancoran Mas',
              alamat_tempat: 'Jl. Margonda Raya No. 1, Depok',
              id_kelurahan: 1,
              id_kecamatan: 1,
              kelurahan: 'Pancoran Mas',
              kecamatan: 'Pancoran Mas',
              notlp: '021-7720001',
              nohp: '081234567890',
              email: 'puskesmas001@depok.go.id',
              izin_ipal: 'IPAL001',
              izin_tps: 'TPS001',
              status_user: 1,
              statusactive_user: 1,
              user_created: 'admin',
              user_updated: 'admin',
              uid: 'uuid-001',
              created_at: '2024-01-01T00:00:00.000Z',
              updated_at: '2024-01-15T10:30:00.000Z',
              limbah: {
                id_laporan_bulanan: 1,
                id_transporter: 1,
                id_user: 1,
                nama_transporter: 'PT Transporter Limbah Sejahtera',
                nama_pemusnah: 'PT Pemusnah Limbah Terpercaya',
                metode_pemusnah: 'Insinerasi',
                berat_limbah_total: '450.25',
                punya_penyimpanan_tps: 1,
                ukuran_penyimpanan_tps: '50 m3',
                punya_pemusnahan_sendiri: 0,
                ukuran_pemusnahan_sendiri: null,
                limbah_b3_covid: '99.00',
                limbah_b3_noncovid: '150.75',
                debit_limbah_cair: '25.50',
                kapasitas_ipal: '100 m3/hari',
                memenuhi_syarat: 1,
                catatan: 'Laporan lengkap dan sesuai standar',
                periode: 1,
                periode_nama: 'Januari',
                tahun: 2024,
                status_laporan_bulanan: 1,
                statusactive_laporan_bulanan: 1,
                user_created: 'puskesmas_001',
                user_updated: null,
                uid: 'laporan-uuid-001',
                created_at: new Date('2024-01-31T23:59:59.000Z'),
                updated_at: new Date('2024-01-31T23:59:59.000Z'),
                link_input_manifest: '/files/manifest_001.pdf',
                link_input_logbook: '/files/logbook_001.pdf',
                link_input_lab_ipal: '/files/lab_ipal_001.pdf',
                link_input_lab_lain: '/files/lab_lain_001.pdf',
                link_input_dokumen_lingkungan_rs: '/files/dokumen_lingkungan_001.pdf',
                link_input_swa_pantau: '/files/swa_pantau_001.pdf',
                link_input_ujilab_cair: '/files/ujilab_cair_001.pdf',
                limbah_b3_nonmedis: '75.25',
                limbah_b3_medis: '125.00',
                limbah_jarum: '35.50',
                limbah_sludge_ipal: '115.00'
              },
              limbah_b3: 200.50,
              limbah_noncovid: 150.75,
              limbah_covid: 99.00,
              limbah_b3_nonmedis: 75.25,
              limbah_b3_medis: 125.00,
              limbah_jarum: 35.50,
              limbah_sludge_ipal: 115.00
            }
          ]
        },
        {
          periode: 2,
          periode_nama: 'Februari',
          total_limbah: 1300.25,
          total_limbah_b3: 650.00,
          total_limbah_covid: 400.25,
          total_limbah_noncovid: 249.75,
          total_limbah_b3_nonmedis: 150.00,
          total_limbah_b3_medis: 500.00,
          total_limbah_jarum: 75.25,
          total_limbah_sludge_ipal: 225.00,
          users: [
            {
              id_user: 2,
              username: 'rs_001',
              nama_user: 'RS Umum Depok',
              level: 3,
              noreg_tempat: 'RS001',
              tipe_tempat: 'Rumah Sakit',
              nama_tempat: 'RS Umum Depok',
              alamat_tempat: 'Jl. Siliwangi No. 50, Depok',
              id_kelurahan: 2,
              id_kecamatan: 2,
              kelurahan: 'Beji',
              kecamatan: 'Beji',
              notlp: '021-7720002',
              nohp: '081234567891',
              email: 'rs001@depok.go.id',
              izin_ipal: 'IPAL002',
              izin_tps: 'TPS002',
              status_user: 1,
              statusactive_user: 1,
              user_created: 'admin',
              user_updated: 'admin',
              uid: 'uuid-002',
              created_at: '2024-01-01T00:00:00.000Z',
              updated_at: '2024-01-15T10:30:00.000Z',
              limbah: {
                id_laporan_bulanan: 2,
                id_transporter: 2,
                id_user: 2,
                nama_transporter: 'PT Eco Waste Management',
                nama_pemusnah: 'PT Green Disposal',
                metode_pemusnah: 'Autoclave + Shredding',
                berat_limbah_total: '850.50',
                punya_penyimpanan_tps: 1,
                ukuran_penyimpanan_tps: '100 m3',
                punya_pemusnahan_sendiri: 1,
                ukuran_pemusnahan_sendiri: '25 m3',
                limbah_b3_covid: '150.00',
                limbah_b3_noncovid: '200.25',
                debit_limbah_cair: '45.75',
                kapasitas_ipal: '200 m3/hari',
                memenuhi_syarat: 1,
                catatan: 'Semua dokumen lengkap, proses sesuai SOP',
                periode: 2,
                periode_nama: 'Februari',
                tahun: 2024,
                status_laporan_bulanan: 1,
                statusactive_laporan_bulanan: 1,
                user_created: 'rs_001',
                user_updated: null,
                uid: 'laporan-uuid-002',
                created_at: new Date('2024-02-29T23:59:59.000Z'),
                updated_at: new Date('2024-02-29T23:59:59.000Z'),
                link_input_manifest: '/files/manifest_002.pdf',
                link_input_logbook: '/files/logbook_002.pdf',
                link_input_lab_ipal: '/files/lab_ipal_002.pdf',
                link_input_lab_lain: '/files/lab_lain_002.pdf',
                link_input_dokumen_lingkungan_rs: '/files/dokumen_lingkungan_002.pdf',
                link_input_swa_pantau: '/files/swa_pantau_002.pdf',
                link_input_ujilab_cair: '/files/ujilab_cair_002.pdf',
                limbah_b3_nonmedis: '125.25',
                limbah_b3_medis: '225.00',
                limbah_jarum: '40.25',
                limbah_sludge_ipal: '135.00'
              },
              limbah_b3: 500.25,
              limbah_noncovid: 200.25,
              limbah_covid: 150.00,
              limbah_b3_nonmedis: 125.25,
              limbah_b3_medis: 225.00,
              limbah_jarum: 40.25,
              limbah_sludge_ipal: 135.00
            }
          ]
        }
      ]
    },
    timestamp: Date.now(),
    timezone: {
      timezone_type: 3,
      timezone: 'Asia/Jakarta'
    }
  };

  // Simulate network delay
  setTimeout(() => {
    res.status(200).json(mockData);
  }, 500);
}